# Generated by Django 4.2.10 on 2024-03-05 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_date', models.DateField()),
                ('field_parameters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_date', models.DateField()),
                ('timestamp', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('switch_sides', models.BooleanField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='heatmap.gamedata')),
            ],
        ),
    ]
